import json
from typing import Dict, Any, List

def generate_eda_notebook(filename: str, profile: Dict[str, Any], target_column: str = "") -> str:
    """
    Generate executable Jupyter Notebook JSON (.ipynb) reproducing the exploratory
    data analysis with pandas, matplotlib, seaborn, and scikit-learn.
    """
    cells: List[Dict[str, Any]] = []

    def add_markdown(text: str):
        cells.append({
            "cell_type": "markdown",
            "metadata": {},
            "source": [line + "\n" for line in text.split("\n")]
        })

    def add_code(code: str):
        cells.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [line + "\n" for line in code.split("\n")]
        })

    # Header cell
    add_markdown(f"""# 🚀 Automated EDAflow Notebook — {filename}
This notebook was automatically generated by **EDAflow Engine**.
It contains complete, executable Python code to inspect, visualize, clean, and model this dataset.
""")

    # Setup cell
    add_code("""import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Visual styling
plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')
plt.rcParams['figure.figsize'] = (10, 5)
plt.rcParams['font.size'] = 11
""")

    # Load dataset cell
    add_code(f"""# Load dataset
# Adjust path if needed
df = pd.read_csv('{filename}')
print(f"Dataset Shape: {{df.shape[0]:,}} rows, {{df.shape[1]}} columns")
df.head()""")

    # Overview & Missingness cell
    add_markdown("## 1. Schema Overview & Missingness Profile")
    add_code("""# Overview summary & missing values
missing_df = pd.DataFrame({
    'Dtype': df.dtypes,
    'Null_Count': df.isnull().sum(),
    'Null_Pct': (df.isnull().sum() / len(df) * 100).round(2),
    'Unique_Count': df.nunique()
}).sort_values(by='Null_Pct', ascending=False)

print(missing_df)

# Missingness bar chart
plt.figure(figsize=(12, 4))
missing_df['Null_Pct'].plot(kind='bar', color='#3b82f6')
plt.title('Missingness Percentage by Column (%)')
plt.ylabel('Missing %')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()""")

    # Numerical distributions
    num_cols = profile.get("numeric_columns", [])
    if num_cols:
        add_markdown("## 2. Numerical Distributions & Outlier Checks")
        num_cols_repr = repr(num_cols[:6])
        add_code(f"""# Numerical distributions for top numeric features
numeric_cols = {num_cols_repr}

fig, axes = plt.subplots(len(numeric_cols), 2, figsize=(14, 3 * len(numeric_cols)))
if len(numeric_cols) == 1:
    axes = np.array([axes])

for idx, col in enumerate(numeric_cols):
    # Histogram + KDE
    sns.histplot(df[col].dropna(), kde=True, ax=axes[idx, 0], color='#6366f1')
    axes[idx, 0].set_title(f'{{col}} — Distribution (Skew: {{df[col].skew():.2f}})')
    
    # Boxplot for outliers
    sns.boxplot(x=df[col].dropna(), ax=axes[idx, 1], color='#10b981')
    axes[idx, 1].set_title(f'{{col}} — Boxplot (IQR Outliers)')

plt.tight_layout()
plt.show()""")

    # Correlations
    if len(num_cols) >= 2:
        add_markdown("## 3. Correlation Heatmap")
        add_code("""# Correlation Matrix Heatmap
corr_matrix = df.select_dtypes(include=[np.number]).corr(method='pearson')

plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', cbar=True, square=True)
plt.title('Pearson Correlation Matrix')
plt.tight_layout()
plt.show()""")

    # Baseline Model
    if target_column and target_column in profile.get("columns", []):
        add_markdown(f"## 4. Machine Learning Baseline for Target: `{target_column}`")
        add_code(f"""# Target column modeling
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression, Ridge

target_col = '{target_column}'
clean_df = df.dropna(subset=[target_col])
X = clean_df.drop(columns=[target_col]).select_dtypes(include=[np.number])
y = clean_df[target_col]

pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(max_iter=500) if y.nunique() <= 10 else Ridge())
])

scores = cross_val_score(pipe, X, y, cv=5)
print(f"5-Fold Cross-Validation Score (Baseline): {{scores.mean():.4f}} (±{{scores.std():.4f}})")
""")

    notebook_dict = {
        "cells": cells,
        "metadata": {
            "language_info": {
                "name": "python",
                "version": "3.11.0"
            },
            "kernelspec": {
                "name": "python3",
                "display_name": "Python 3"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 5
    }

    return json.dumps(notebook_dict, indent=2)
